[package]
name = "vote"
version = "0.1.0"
authors = ["eokovacs"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket", rev = "9671115796e42865eaebd020ac27542802027b02" }
askama = "0.10"
sqlx = { version = "0.4", features = ["runtime-async-std-rustls"] }
async-std= "1.8"
twilight-oauth2 = { git = "https://github.com/twilight-rs/oauth2", rev = "2de30560ef8da8956890b5e8872269197a374d37" }
twilight-model = "0.2"
dotenv = "0.15"
envy = "0.4"
serde = { version = "1.0", features  = ["derive"] }